// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class AgeGroup
{
    public int GroupId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int MinAge { get; set; }

    public int MaxAge { get; set; }

    public virtual ICollection<Assessment> Assessments { get; set; } = new List<Assessment>();
}