// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Appointment
{
    public int AppointmentId { get; set; }

    public int? UserId { get; set; }

    public int? ConsultantId { get; set; }

    public DateTime CreatedDate { get; set; }

    public string MeetingLink { get; set; }

    public int? Material { get; set; }

    public string Status { get; set; }

    public int? AvailabilityId { get; set; }

    public virtual ConsultantsAvailability Availability { get; set; }

    public virtual Consultant Consultant { get; set; }

    public virtual Document MaterialNavigation { get; set; }

    public virtual User User { get; set; }
}