// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class AssessmentOption
{
    public int OptionId { get; set; }

    public int? QuestionId { get; set; }

    public string OptionText { get; set; }

    public string OptionValue { get; set; }

    public int? DisplayOrder { get; set; }

    public virtual AssessmentQuestion Question { get; set; }
}