// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Assessment
{
    public int AssessmentId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int? AssessmentType { get; set; }

    public int? AgeGroup { get; set; }

    public DateTime? CreatedDate { get; set; }

    public bool? IsActive { get; set; }

    public virtual AgeGroup AgeGroupNavigation { get; set; }

    public virtual ICollection<AssessmentQuestion> AssessmentQuestions { get; set; } = new List<AssessmentQuestion>();

    public virtual AssessmentType AssessmentTypeNavigation { get; set; }

    public virtual ICollection<UserAssessment> UserAssessments { get; set; } = new List<UserAssessment>();
}