// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class AssessmentQuestion
{
    public int QuestionId { get; set; }

    public int? AssessmentId { get; set; }

    public string QuestionText { get; set; }

    public string QuestionType { get; set; }

    public int? DisplayOrder { get; set; }

    public bool? IsRequired { get; set; }

    public virtual Assessment Assessment { get; set; }

    public virtual ICollection<AssessmentOption> AssessmentOptions { get; set; } = new List<AssessmentOption>();
}