// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Certification
{
    public int UserId { get; set; }

    public int CourseId { get; set; }

    public string Name { get; set; }

    public string CertificationCode { get; set; }

    public string CertificationUrl { get; set; }

    public DateOnly? AchievedDate { get; set; }

    public virtual Course Course { get; set; }

    public virtual User User { get; set; }
}