// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Comment
{
    public int CommentId { get; set; }

    public int? UserId { get; set; }

    public int? BlogId { get; set; }

    public string Content { get; set; }

    public DateTime? PostDate { get; set; }

    public virtual Blog Blog { get; set; }

    public virtual User User { get; set; }
}