// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Repositories.Models;

public partial class CourseRegister
{
    public int UserId { get; set; }

    public int CourseId { get; set; }

    public DateTime? RegisterDate { get; set; }

    [JsonIgnore]
	public virtual Course Course { get; set; }

    [JsonIgnore]
	public virtual User User { get; set; }
}