// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Course
{
    public int CourseId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int Duration { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string VideoUrl { get; set; }

    public string DocumentContent { get; set; }

    public int? Category { get; set; }

    public virtual CourseCategory CategoryNavigation { get; set; }

    public virtual ICollection<Certification> Certifications { get; set; } = new List<Certification>();

    public virtual ICollection<CourseQuestion> CourseQuestions { get; set; } = new List<CourseQuestion>();

    public virtual ICollection<CourseRegister> CourseRegisters { get; set; } = new List<CourseRegister>();

    public virtual ICollection<UserAnswer> UserAnswers { get; set; } = new List<UserAnswer>();
}