// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class CourseQuestion
{
    public int QuestionId { get; set; }

    public int? CourseId { get; set; }

    public string QuestionText { get; set; }

    public string QuestionType { get; set; }

    public int DisplayOrder { get; set; }

    public bool? IsRequired { get; set; }

    public virtual Course Course { get; set; }

    public virtual ICollection<CourseQuestionOption> CourseQuestionOptions { get; set; } = new List<CourseQuestionOption>();

    public virtual ICollection<UserAnswer> UserAnswers { get; set; } = new List<UserAnswer>();
}