// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Document
{
    public int MaterialId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();
}