// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class UserAssessment
{
    public int UserAssessmentId { get; set; }

    public int? AssessmentId { get; set; }

    public int? UserId { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? CompletedTime { get; set; }

    public decimal? Score { get; set; }

    public int? RiskLevel { get; set; }

    public virtual Assessment Assessment { get; set; }

    public virtual RiskLevel RiskLevelNavigation { get; set; }

    public virtual User User { get; set; }
}